-- Your SQL goes here
CREATE TABLE books (
	id INTEGER NOT NULL PRIMARY KEY,
	title VARCHAR NOT NULL,
	author VARCHAR NOT NULL,
	genre VARCHAR NOT NULL,
	rating REAL NOT NULL,
	status VARCHAR NOT NULL
)
